import { useEffect, useMemo, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { AuthRejectedError, getStudentEvidence, getStudentMaterial, listStudentMaterials, publishPracticeMaterial, submitStudentResponse } from "../lib/api";
import { demoClassId } from "../lib/supabase";
import type { ActivityGuide, Assessment, LessonPlan, ReviewReport } from "../types/teachingPack";
import type { PublishPracticeMaterialRequest, StudentPracticeItem } from "../types/studentSection";

function useAccessToken() {
  const { session, markRequestRejected } = useAuth();
  if (!session?.access_token) throw new Error("Necesitas iniciar sesión para continuar.");
  return { accessToken: session.access_token, markRequestRejected };
}

function requestError(caught: unknown): string {
  return caught instanceof Error ? caught.message : "No pudimos completar esta acción.";
}

function ItemPrompt({ item }: { item: StudentPracticeItem }) {
  const snapshot = item.item_snapshot as { question?: unknown; options?: unknown };
  const question = typeof snapshot.question === "string" ? snapshot.question : "Ítem publicado";
  const options = Array.isArray(snapshot.options)
    ? snapshot.options.filter((option): option is { label: string; text: string } => typeof option === "object" && option !== null && typeof (option as { label?: unknown }).label === "string" && typeof (option as { text?: unknown }).text === "string")
    : [];
  return <><p className="font-medium leading-7 text-stone-900">{question}</p>{options.length > 0 && <ul className="mt-3 space-y-2 text-sm text-stone-700">{options.map((option) => <li key={option.label}><b>{option.label}.</b> {option.text}</li>)}</ul>}</>;
}

export function StudentMaterialsView({ onOpen, onBack }: { onOpen: (releaseId: string) => void; onBack: () => void }) {
  const { accessToken, markRequestRejected } = useAccessToken();
  const [releases, setReleases] = useState<Awaited<ReturnType<typeof listStudentMaterials>>>([]);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; void listStudentMaterials(accessToken).then((data) => { if (active) { setReleases(data); setState("ready"); } }).catch((caught) => { if (!active) return; if (caught instanceof AuthRejectedError) void markRequestRejected(); setError(requestError(caught)); setState("error"); }); return () => { active = false; }; }, [accessToken, markRequestRejected]);
  return <section className="mx-auto mt-12 max-w-3xl"><button className="no-print text-sm font-semibold text-[#195b4e] underline" onClick={onBack}>← Volver</button><p className="mt-8 text-sm font-bold tracking-[.12em] text-[#3b7969]">PRÁCTICA</p><h1 className="mt-3 font-serif text-4xl text-stone-900">Mis materiales</h1><p className="mt-3 max-w-2xl leading-7 text-stone-600">Aquí aparecen únicamente los materiales que tu profesora publicó para tu curso.</p>{state === "loading" && <p className="mt-7 rounded-2xl bg-white p-5 text-stone-600">Buscando tus materiales…</p>}{state === "error" && <p className="mt-7 rounded-xl bg-rose-50 p-4 text-rose-900">{error}</p>}{state === "ready" && !releases.length && <div className="mt-7 rounded-2xl border border-stone-200 bg-white p-6"><p className="font-semibold text-stone-900">Aún no tienes material publicado.</p><p className="mt-1 text-sm text-stone-600">Cuando tu profesora publique una guía para tu curso, aparecerá aquí.</p></div>}<div className="mt-7 space-y-4">{releases.map((release) => <article key={release.release_id} className="rounded-2xl border border-stone-200 bg-white p-6 shadow-[0_12px_35px_-28px_rgba(28,60,51,.45)]"><p className="text-xs font-bold tracking-[.12em] text-[#3b7969]">PUBLICADO PARA TU CURSO</p><h2 className="mt-2 font-serif text-2xl text-stone-900">{release.title}</h2><p className="mt-2 text-sm text-stone-500">Disponible desde {new Date(release.released_at).toLocaleDateString("es-CL")}</p><button onClick={() => onOpen(release.release_id)} className="mt-5 rounded-lg bg-[#195b4e] px-4 py-2.5 text-sm font-semibold text-white">Abrir práctica</button></article>)}</div></section>;
}

export function StudentPracticeView({ releaseId, onBack }: { releaseId: string; onBack: () => void }) {
  const { accessToken, markRequestRejected } = useAccessToken();
  const [material, setMaterial] = useState<Awaited<ReturnType<typeof getStudentMaterial>> | null>(null);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [receipts, setReceipts] = useState<Record<string, Awaited<ReturnType<typeof submitStudentResponse>>>>({});
  const [sending, setSending] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; void getStudentMaterial(releaseId, accessToken).then((data) => { if (active) setMaterial(data); }).catch((caught) => { if (!active) return; if (caught instanceof AuthRejectedError) void markRequestRejected(); setError(requestError(caught)); }); return () => { active = false; }; }, [releaseId, accessToken, markRequestRejected]);
  const submit = async (item: StudentPracticeItem) => { const answer = answers[item.id]?.trim(); if (!answer) return; setSending(item.id); setError(null); try { const receipt = await submitStudentResponse(item.id, answer, accessToken); setReceipts((current) => ({ ...current, [item.id]: receipt })); } catch (caught) { if (caught instanceof AuthRejectedError) void markRequestRejected(); setError(requestError(caught)); } finally { setSending(null); } };
  if (error && !material) return <section className="mx-auto mt-12 max-w-3xl"><button className="text-sm font-semibold text-[#195b4e] underline" onClick={onBack}>← Mis materiales</button><p className="mt-6 rounded-xl bg-rose-50 p-4 text-rose-900">{error}</p></section>;
  if (!material) return <section className="mx-auto mt-12 max-w-3xl"><p className="text-stone-600">Abriendo material…</p></section>;
  return <section className="mx-auto mt-12 max-w-3xl"><button className="no-print text-sm font-semibold text-[#195b4e] underline" onClick={onBack}>← Mis materiales</button><p className="mt-8 text-sm font-bold tracking-[.12em] text-[#3b7969]">PRÁCTICA PUBLICADA</p><h1 className="mt-3 font-serif text-4xl text-stone-900">{material.title}</h1><p className="mt-3 text-stone-600">Responde con calma. Algunas respuestas pueden requerir revisión de tu profesora.</p>{error && <p className="mt-5 rounded-xl bg-rose-50 p-4 text-rose-900">{error}</p>}<div className="mt-8 space-y-5">{material.items.map((item) => { const receipt = receipts[item.id]; const teacherJudgment = item.validation_mode === "teacher_judgment"; return <article key={item.id} className="rounded-2xl border border-stone-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-bold tracking-[.12em] text-[#c36c3e]">ÍTEM {item.ordinal}</p>{item.evidence_objective_code && <p className="rounded-full bg-[#edf5f0] px-3 py-1 text-xs font-semibold text-[#195b4e]">{item.evidence_objective_code}</p>}</div><div className="mt-4"><ItemPrompt item={item} /></div><label className="field mt-5"><span>Tu respuesta</span><textarea rows={3} value={answers[item.id] ?? ""} disabled={Boolean(receipt)} onChange={(event) => setAnswers((current) => ({ ...current, [item.id]: event.target.value }))} /></label>{!receipt && <button disabled={sending === item.id || !(answers[item.id]?.trim())} onClick={() => void submit(item)} className="mt-4 rounded-lg bg-[#195b4e] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{sending === item.id ? "Enviando…" : "Enviar respuesta"}</button>}{receipt && <p className={`mt-4 rounded-xl p-4 text-sm ${teacherJudgment || receipt.feedback_state !== "verified" ? "bg-stone-100 text-stone-700" : "bg-emerald-50 text-emerald-950"}`}>{teacherJudgment ? "Respuesta enviada. Tu profesora la revisará." : receipt.feedback_message}</p>}</article>; })}</div></section>;
}

export function TeacherEvidenceView({ onBack }: { onBack: () => void }) {
  const { accessToken, markRequestRejected } = useAccessToken();
  const [rows, setRows] = useState<Awaited<ReturnType<typeof getStudentEvidence>>>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!demoClassId) { setError("Falta VITE_DEMO_CLASS_ID para consultar la evidencia del curso de demostración."); return; } let active = true; void getStudentEvidence(demoClassId, accessToken).then((data) => { if (active) setRows(data); }).catch((caught) => { if (!active) return; if (caught instanceof AuthRejectedError) void markRequestRejected(); setError(requestError(caught)); }); return () => { active = false; }; }, [accessToken, markRequestRejected]);
  const grouped = useMemo(() => rows.reduce<Record<string, typeof rows>>((all, row) => { (all[row.objective_code] ??= []).push(row); return all; }, {}), [rows]);
  const studentLabel = (id: string) => {
    const name = rows.find((row) => row.student_id === id)?.student_full_name?.trim();
    return name || `Estudiante · ${id.slice(0, 8)}`;
  };
  return <section className="mx-auto mt-12 max-w-5xl"><button className="no-print text-sm font-semibold text-[#195b4e] underline" onClick={onBack}>← Volver</button><p className="mt-8 text-sm font-bold tracking-[.12em] text-[#c36c3e]">EVIDENCIA DE RESPUESTAS</p><h1 className="mt-3 font-serif text-4xl text-stone-900">Lo declarado, lo atestado y lo que respondieron.</h1><div className="mt-6 rounded-2xl border border-[#e8bd77] bg-[#fff5df] p-5 text-amber-950"><p className="font-semibold">Estos datos no determinan dominio ni rendimiento.</p><p className="mt-1 text-sm leading-6">Muestran respuestas a ítems que tú etiquetaste con cada OA. La interpretación pedagógica sigue siendo de la profesora.</p></div>{error && <p className="mt-6 rounded-xl bg-rose-50 p-4 text-rose-900">{error}</p>}{!error && !rows.length && <p className="mt-6 rounded-2xl bg-white p-5 text-stone-600">Aún no hay evidencia de respuestas para este curso.</p>}<div className="mt-8 space-y-7">{Object.entries(grouped).map(([objectiveCode, objectiveRows]) => <section key={objectiveCode} className="rounded-2xl border border-stone-200 bg-white p-6"><h2 className="font-serif text-2xl text-stone-900">{objectiveCode}</h2><p className="mt-1 text-sm text-stone-600">Capas separadas de evidencia para este OA.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#edf5f0] text-xs uppercase tracking-wide text-[#195b4e]"><tr><th className="p-3">Estudiante</th><th className="p-3">Declarado</th><th className="p-3">Atestado</th><th className="p-3">Evidencia de respuestas</th></tr></thead><tbody>{objectiveRows.map((row) => <tr key={row.student_id} className="border-b border-stone-100 last:border-0"><td className="p-3 font-semibold text-stone-800">{studentLabel(row.student_id)}</td><td className="p-3 text-stone-700">{row.declared_publication_count} publicación{row.declared_publication_count === 1 ? "" : "es"} declarada{row.declared_publication_count === 1 ? "" : "s"}</td><td className="p-3 text-stone-700">{row.attested_item_count} ítem{row.attested_item_count === 1 ? "" : "s"} que etiquetaste con {row.objective_code}</td><td className="p-3"><span className={`inline-block rounded-xl px-3 py-2 ${row.state === "evidencia_suficiente" ? "bg-emerald-50 text-emerald-950" : "bg-stone-100 text-stone-700"}`}>{row.state === "evidencia_insuficiente" ? `Evidencia insuficiente · ${row.wording}` : row.wording}</span></td></tr>)}</tbody></table></div></section>)}</div></section>;
}

export function TeacherPublishView({ plan, guide, assessment, review }: { plan: LessonPlan; guide: ActivityGuide; assessment: Assessment; review: ReviewReport }) {
  const { accessToken, markRequestRejected } = useAccessToken();
  const verifiedObjectives = plan.curriculum_alignment.objectives;
  const [itemObjectives, setItemObjectives] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [published, setPublished] = useState<{ releaseId: string; note: string } | null>(null);
  const reviewReference = review.status === "clean" ? "revisión limpia" : "revisión con observaciones visibles";
  const publish = async () => { if (!demoClassId) { setError("Falta VITE_DEMO_CLASS_ID para publicar en el curso de demostración."); return; } setBusy(true); setError(null); try { const request: PublishPracticeMaterialRequest = { class_id: demoClassId, source_pack_reference: `pack-${plan.title}`, source_pack_version_reference: null, source_review_reference: reviewReference, title: assessment.title, content_snapshot: { lesson_plan: plan, activities: guide, assessment }, declared_objective_codes: verifiedObjectives.map((objective) => objective.code), attestation_statement_version: "student-practice-v1", items: assessment.items.map((item, index) => ({ source_assessment_item_id: item.id, ordinal: index + 1, item_snapshot: item as unknown as Record<string, unknown>, requested_evidence_objective_code: itemObjectives[item.id] || null, deterministic_validator_candidate: null })) }; const response = await publishPracticeMaterial(request, accessToken); setPublished({ releaseId: response.release_id, note: response.note }); } catch (caught) { if (caught instanceof AuthRejectedError) void markRequestRejected(); setError(requestError(caught)); } finally { setBusy(false); } };
  return <section className="no-print mx-auto mb-8 max-w-6xl rounded-2xl border border-[#c6d8d1] bg-[#edf5f0] p-6"><p className="text-xs font-bold tracking-[.12em] text-[#195b4e]">PRÁCTICA PARA ESTUDIANTES</p><h2 className="mt-2 font-serif text-2xl text-stone-900">Publicar para mi curso</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-700">Al publicar, atestiguas qué OA verificados etiqueta cada ítem. Los ítems sin OA seleccionado se publican como práctica, pero no generan evidencia curricular.</p>{!verifiedObjectives.length && <p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-950">Este pack no tiene OA verificados. Puedes publicarlo solo como práctica; no producirá evidencia curricular.</p>}<div className="mt-5 space-y-3">{assessment.items.map((item, index) => <div key={item.id} className="rounded-xl border border-white/80 bg-white/75 p-4"><p className="font-semibold text-stone-900">Ítem {index + 1}</p><p className="mt-1 text-sm text-stone-600">{item.question}</p><label className="field mt-3"><span>OA que atestiguo para este ítem <em>(opcional: sin selección = práctica)</em></span><select value={itemObjectives[item.id] ?? ""} onChange={(event) => setItemObjectives((current) => ({ ...current, [item.id]: event.target.value }))}><option value="">Solo práctica, sin evidencia OA</option>{verifiedObjectives.map((objective) => <option key={objective.code} value={objective.code}>{objective.code} · Verificado</option>)}</select></label></div>)}</div>{error && <p className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-900">{error}</p>}{published ? <div className="mt-5 rounded-xl bg-white p-4 text-sm text-stone-800"><p className="font-semibold text-[#195b4e]">Material publicado.</p><p className="mt-1">{published.note}</p><p className="mt-2 text-xs text-stone-500">Release para la lista de estudiantes: {published.releaseId}</p></div> : <button disabled={busy} onClick={() => void publish()} className="mt-5 rounded-lg bg-[#195b4e] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Publicando…" : "Publicar para mi curso"}</button>}</section>;
}
