import type { ActivityGuide, Assessment, LessonPlan } from "../types/teachingPack";
import { ResultSection } from "./ResultSection";

const List = ({ items }: { items: string[] }) => <ul className="space-y-2">{items.map((item) => <li key={item}>• {item}</li>)}</ul>;
export function TeachingPackResults({ plan, guide, assessment }: { plan: LessonPlan; guide: ActivityGuide; assessment: Assessment }) {
  const grouped = guide.activities.reduce<Record<string, typeof guide.activities>>((all, activity) => { (all[activity.stage_name] ??= []).push(activity); return all; }, {});
  return <div className="teaching-pack mt-12 space-y-10"><div className="no-print flex justify-between"><h1 className="font-serif text-4xl text-stone-900">{plan.title}</h1><button onClick={() => window.print()}>Imprimir pack</button></div>
    <ResultSection eyebrow="Plan de clase" title="Propósito y ruta de aprendizaje"><p>{plan.subject} · {plan.grade_level} · {plan.duration_minutes} min</p><div className="mt-5 rounded-xl bg-emerald-50 p-4"><b>{plan.curriculum_alignment.status}</b>{plan.curriculum_alignment.objectives.map((oa) => <p key={oa.code}><b>{oa.code}</b> · {oa.description}</p>)}<List items={plan.curriculum_alignment.notes} /></div><List items={plan.learning_objectives} /><div className="mt-5">{plan.stages.map((stage) => <p key={stage.name}><b>{stage.name} · {stage.duration_minutes} min:</b> {stage.purpose}</p>)}</div></ResultSection>
    <div className="print-break"><ResultSection eyebrow="Actividades" title={guide.title}>{plan.stages.map((stage) => <section key={stage.name} className="mt-6"><h3>{stage.name}</h3>{(grouped[stage.name] ?? []).map((activity) => <article key={activity.title} className="mt-3 rounded-xl bg-[#fbfaf6] p-4"><b>{activity.title} · {activity.duration_minutes} min · {activity.grouping}</b><List items={activity.teacher_instructions} /><p><b>Producto:</b> {activity.expected_student_output}</p><p><b>Apoyo:</b> {activity.differentiation.support}</p><p><b>Extensión:</b> {activity.differentiation.extension}</p></article>)}</section>)}</ResultSection></div>
    <div className="print-break"><ResultSection eyebrow="Evaluación" title={assessment.title}><p>{assessment.suggested_application_minutes} min · {assessment.total_points} puntos</p><table className="mt-4 w-full text-left text-sm"><tbody>{assessment.specification_table.map((row) => <tr key={row.learning_objective}><td>{row.learning_objective}</td><td>{row.item_ids.join(", ")}</td><td>{row.total_points} pts</td><td>{row.cognitive_levels.join(", ")}</td></tr>)}</tbody></table>{assessment.items.map((item) => <article key={item.id} className="mt-5 rounded-xl bg-[#fbfaf6] p-4"><p><b>{item.id}. {item.question}</b> ({item.points} pts)</p>{item.options.map((option) => <p key={option.label} className={option.label === item.correct_option_label ? "font-bold text-[#195b4e]" : ""}>{option.label}. {option.text}{option.label === item.correct_option_label && " ✓"}</p>)}{item.correct_option_label && <p><b>Alternativa correcta:</b> {item.correct_option_label}</p>}<p><b>Criterio / respuesta esperada:</b> {item.expected_answer}</p></article>)}{assessment.rubric.map((criterion) => <article key={criterion.criterion} className="mt-4 rounded-xl border p-4"><b>{criterion.criterion}</b><p>Logrado: {criterion.levels.logrado}</p><p>En proceso: {criterion.levels.en_proceso}</p><p>Requiere apoyo: {criterion.levels.requiere_apoyo}</p></article>)}</ResultSection></div>
  </div>;
}
