import type { ActivityGuide, Assessment, LessonPlan, MaterialPack, ReviewFinding, ReviewReport } from "../types/teachingPack";
import { ResultSection } from "./ResultSection";

const List = ({ items }: { items: string[] }) => <ul className="space-y-2">{items.map((item) => <li key={item}>• {item}</li>)}</ul>;
const printTarget = (target: "full" | "student" | "materials") => { document.body.dataset.printTarget = target; window.print(); window.setTimeout(() => delete document.body.dataset.printTarget, 0); };

function ReviewNotes({ findings }: { findings: ReviewFinding[] }) {
  if (!findings.length) return null;
  const tone = { bloqueante: "border-rose-300 bg-rose-50 text-rose-950", importante: "border-amber-300 bg-amber-50 text-amber-950", menor: "border-stone-300 bg-stone-50 text-stone-800" };
  return <aside className="no-print mt-6 space-y-3" aria-label="Observaciones de revisión de Clara"><p className="text-sm font-semibold text-stone-700">Observaciones de Clara sobre el material generado</p>{findings.map((finding) => <article key={finding.id} className={`rounded-xl border-l-4 p-4 ${tone[finding.severity]}`}><div className="flex flex-wrap gap-2 text-xs font-bold uppercase tracking-wide"><span>{finding.severity}</span><span className="normal-case font-semibold tracking-normal">{finding.artifact_id}</span></div><p className="mt-2 font-medium">{finding.description}</p><p className="mt-2 text-sm"><b>Sugerencia:</b> {finding.suggested_correction}</p></article>)}</aside>;
}

export function TeachingPackResults({ plan, guide, assessment, review, materials, onGenerateMaterials, materialsBusy, onReplay }: { plan: LessonPlan; guide: ActivityGuide; assessment: Assessment; review: ReviewReport; materials: MaterialPack | null; onGenerateMaterials: () => void; materialsBusy: boolean; onReplay?: () => void }) {
  const grouped = guide.activities.reduce<Record<string, typeof guide.activities>>((all, activity) => { (all[activity.stage_name] ??= []).push(activity); return all; }, {});
  const findingsFor = (agent: ReviewFinding["responsible_agent"]) => review.findings.filter((finding) => finding.responsible_agent === agent);
  const passed = review.status === "clean" && !review.findings.length;
  const nav = [["plan", "Plan"], ["actividades", "Actividades"], ["evaluacion", "Evaluación"], ["materiales", "Materiales"]] as const;
  return <div className="teaching-pack mt-12 space-y-10">
    <header className="border-b border-stone-200 pb-7"><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#3b7969]">Pack de enseñanza</p><h1 className="mt-2 font-serif text-4xl text-stone-900">{plan.title}</h1><div className={`mt-4 max-w-2xl rounded-xl px-4 py-3 text-sm ${passed ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-950"}`}><b>{passed ? "Revisión de coherencia superada" : "Clara revisó el pack con transparencia"}</b><p className="mt-1">{passed ? "Plan, actividades y evaluación fueron revisados en conjunto antes de llegar a ti." : "Estas observaciones se refieren al material de Clara, no a tu solicitud."}</p></div></header>
    <div className="no-print sticky top-3 z-20 rounded-2xl border border-stone-200 bg-[#fffcf7]/95 p-3 shadow-sm backdrop-blur"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><nav className="flex flex-wrap gap-1" aria-label="Secciones del pack">{nav.map(([id, label]) => <a key={id} href={`#${id}`} className="rounded-lg px-3 py-2 text-sm font-semibold text-stone-600 hover:bg-stone-100">{label}</a>)}</nav><div className="flex flex-wrap items-center gap-2"><div className="flex items-center rounded-lg border border-stone-200 bg-white p-1"><span className="px-2 text-xs font-bold uppercase tracking-wide text-stone-500">Imprimir</span><button onClick={() => printTarget("full")} className="rounded-md px-2 py-1.5 text-sm hover:bg-stone-100">Pack</button><button onClick={() => printTarget("student")} className="rounded-md px-2 py-1.5 text-sm hover:bg-stone-100">Evaluación</button>{materials && <button onClick={() => printTarget("materials")} className="rounded-md px-2 py-1.5 text-sm hover:bg-stone-100">Materiales</button>}</div><button disabled={materialsBusy || !!materials} onClick={onGenerateMaterials} className="rounded-lg bg-[#195b4e] px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">{materials ? "Materiales listos" : materialsBusy ? "Preparando materiales…" : "Generar materiales"}</button>{onReplay && <button onClick={onReplay} className="ml-1 text-xs font-semibold text-stone-400 underline hover:text-stone-600">Vista previa · reproducir</button>}</div></div></div>
    <section id="plan" className="scroll-mt-28"><ResultSection eyebrow="Plan de clase" title="Propósito y ruta de aprendizaje"><p>{plan.subject} · {plan.grade_level} · {plan.duration_minutes} min</p><div className="mt-5 rounded-xl bg-emerald-50 p-4"><b>{plan.curriculum_alignment.status}</b>{plan.curriculum_alignment.objectives.map((oa) => <p key={oa.code}><b>{oa.code}</b> · {oa.description}</p>)}<List items={plan.curriculum_alignment.notes} /></div><List items={plan.learning_objectives} /><div className="mt-6 grid gap-3 sm:grid-cols-2">{plan.stages.map((stage) => <article key={stage.name} className="rounded-xl border border-stone-200 bg-[#fbfaf6] p-4"><p className="text-xs font-bold uppercase tracking-wide text-[#3b7969]">{stage.duration_minutes} min</p><b>{stage.name}</b><p className="mt-1 text-sm">{stage.purpose}</p></article>)}</div><ReviewNotes findings={findingsFor("planner")} /></ResultSection></section>
    <section id="actividades" className="print-break scroll-mt-28"><ResultSection eyebrow="Actividades" title={guide.title}>{plan.stages.map((stage) => <section key={stage.name} className="mt-6"><h3>{stage.name}</h3>{(grouped[stage.name] ?? []).map((activity) => <article key={activity.id} className="mt-3 rounded-xl bg-[#fbfaf6] p-4"><b>{activity.title} · {activity.duration_minutes} min · {activity.grouping}</b><List items={activity.teacher_instructions} /><p><b>Producto:</b> {activity.expected_student_output}</p><p><b>Apoyo:</b> {activity.differentiation.support}</p><p><b>Extensión:</b> {activity.differentiation.extension}</p></article>)}</section>)}<ReviewNotes findings={findingsFor("designer")} /></ResultSection></section>
    <section id="evaluacion" className="print-break scroll-mt-28"><ResultSection eyebrow="Evaluación docente" title={assessment.title}><p>{assessment.suggested_application_minutes} min · {assessment.total_points} puntos</p><table className="mt-4 w-full text-left text-sm"><tbody>{assessment.specification_table.map((row) => <tr key={row.learning_objective}><td>{row.learning_objective}</td><td>{row.item_ids.join(", ")}</td><td>{row.total_points} pts</td><td>{row.cognitive_levels.join(", ")}</td></tr>)}</tbody></table>{assessment.items.map((item) => <article key={item.id} className="mt-5 rounded-xl bg-[#fbfaf6] p-4"><p><b>{item.id}. {item.question}</b> ({item.points} pts)</p>{item.options.map((option) => <p key={option.label} className={option.label === item.correct_option_label ? "font-bold text-[#195b4e]" : ""}>{option.label}. {option.text}{option.label === item.correct_option_label && " ✓"}</p>)}{item.correct_option_label && <p><b>Alternativa correcta:</b> {item.correct_option_label}</p>}<p><b>Criterio / respuesta esperada:</b> {item.expected_answer}</p></article>)}{assessment.rubric.map((criterion) => <article key={criterion.criterion} className="mt-4 rounded-xl border p-4"><b>{criterion.criterion}</b><p>Logrado: {criterion.levels.logrado}</p><p>En proceso: {criterion.levels.en_proceso}</p><p>Requiere apoyo: {criterion.levels.requiere_apoyo}</p></article>)}<ReviewNotes findings={findingsFor("assessment")} /></ResultSection></section>
    <section className="student-assessment print-student print-break"><ResultSection eyebrow="Evaluación para estudiantes" title={assessment.title}><List items={assessment.instructions} />{assessment.items.map((item) => <article key={item.id} className="mt-5"><p><b>{item.id}. {item.question}</b> ({item.points} pts)</p>{item.options.map((option) => <p key={option.label}>○ {option.label}. {option.text}</p>)}{item.type !== "selección múltiple" && <div className="mt-3 h-20 border-b border-stone-400" />}</article>)}</ResultSection></section>
    {materials && <section id="materiales" className="print-break scroll-mt-28"><ResultSection eyebrow="Materiales imprimibles" title={materials.title}>{materials.materials.map((material) => <article key={material.id} className="print-break mt-5 rounded-xl border border-stone-200 p-6"><p className="text-xs font-bold uppercase tracking-wide text-[#3b7969]">{material.source_material_label}</p><h3 className="mt-2">{material.title}</h3><List items={material.student_instructions} />{material.content.map((block, index) => <div key={index} className="mt-4">{block.title && <b>{block.title}</b>}{block.content && <p>{block.content}</p>}{block.type === "tabla" && <table className="mt-2 w-full border-collapse text-sm"><tbody><tr>{block.columns.map((column) => <th key={column} className="border p-2 text-left">{column}</th>)}</tr>{block.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, cellIndex) => <td key={cellIndex} className="h-8 border p-2">{cell}</td>)}</tr>)}</tbody></table>}{block.type === "tarjetas" && <div className="mt-2 grid grid-cols-2 gap-2">{block.cards.map((card, cardIndex) => <div key={cardIndex} className="border p-3">{card.front}<hr className="my-2" />{card.back}</div>)}</div>}</div>)}</article>)}<ReviewNotes findings={findingsFor("materials")} /></ResultSection></section>}
  </div>;
}
