import { useState } from "react";
import { GenerationProgress } from "./components/GenerationProgress";
import { LessonRequestForm } from "./components/LessonRequestForm";
import { TeachingPackResults } from "./components/TeachingPackResults";
import { generateTeachingPackStream } from "./lib/api";
import type { ActivityGuide, Assessment, LessonPlan, LessonRequest } from "./types/teachingPack";

export default function App() { const [screen, setScreen] = useState<"request" | "generating" | "results">("request"); const [plan, setPlan] = useState<LessonPlan | null>(null); const [guide, setGuide] = useState<ActivityGuide | null>(null); const [assessment, setAssessment] = useState<Assessment | null>(null); const [planner, setPlanner] = useState<"pending" | "working" | "done">("pending"); const [designer, setDesigner] = useState<"pending" | "working" | "done">("pending"); const [error, setError] = useState<string | null>(null);
async function start(request: LessonRequest) { setScreen("generating"); setPlan(null); setGuide(null); setAssessment(null); setPlanner("working"); setDesigner("pending"); setError(null); try { await generateTeachingPackStream(request, (event) => { if (event.type === "planner_started") setPlanner("working"); if (event.type === "planner_completed") { setPlan(event.plan); setPlanner("done"); } if (event.type === "designer_started") setDesigner("working"); if (event.type === "designer_completed") { setGuide(event.activities); setDesigner("done"); } if (event.type === "assessment_completed") { setAssessment(event.assessment); setScreen("results"); } if (event.type === "failure") { setError(event.message); setScreen("request"); } }); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible preparar tu material."); setScreen("request"); } }
return <main className="min-h-screen bg-[#f7f4ed]"><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12"><header className="no-print flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#195b4e] font-serif text-xl text-white">C</div><div><p className="font-serif text-xl font-semibold text-stone-900">Clara</p><p className="text-xs text-stone-500">Compañera de planificación docente</p></div></div></header>{screen === "request" && <div className="mx-auto mt-14 max-w-3xl"><p className="text-sm font-bold tracking-[.12em] text-[#c36c3e]">PLANIFICA CON CALMA</p><h1 className="mt-4 font-serif text-5xl leading-[1.03] text-stone-900 sm:text-6xl">Una buena clase empieza con una intención clara.</h1><div className="mt-10"><LessonRequestForm onSubmit={start} />{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-800">{error}</p>}</div></div>}{screen === "generating" && <GenerationProgress planner={planner} designer={designer} plan={plan} guide={guide} />}{screen === "results" && plan && guide && assessment && <TeachingPackResults plan={plan} guide={guide} assessment={assessment} />}</div></main>; }
